CREATE TABLE CUSTOMER(
  CUSTOMER_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  FIRST_NAME VARCHAR(64),
  LAST_NAME VARCHAR(64),
  STATUS VARCHAR(64),
  CREATION_DATE BIGINT,
  EMAIL_ADDRESS VARCHAR(64),
  ADDRESS VARCHAR(64),
  COUNTRY VARCHAR(32),
  STATE VARCHAR(12),
  PHONE_NUMBER VARCHAR(24)
);

CREATE TABLE APPLICATION_USER(
  USER_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  FIRST_NAME VARCHAR(64),
  LAST_NAME VARCHAR(64),
  EMAIL VARCHAR(64),
  PASSWORD VARCHAR(64),
  USER_ROLE VARCHAR(64)
);

CREATE TABLE NOTE(
  NOTE_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  CUSTOMER_ID BIGINT NOT NULL,
  CREATED_BY VARCHAR(128) NOT NULL,
  UPDATED_BY VARCHAR(128) NOT NULL,
  SUMMARY VARCHAR(255) NOT NULL,
  CREATE_DATE BIGINT,
  UPDATE_DATE BIGINT
);

CREATE INDEX IDX_CUS_ID_ ON CUSTOMER(CUSTOMER_ID);
